name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.FTP_USER }}
        DEBUG_SECRET_KEY: ${{ secrets.FTP_PASS }}
        DEBUG_DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        echo $DEBUG_SECRET_KEY >> secrets.txt
        echo $DEBUG_DATABASE_URL >> secrets.txt
    - name: Test tmate connectivity
      run: |
          echo "Testing DNS..."
          getent hosts ssh.tmate.io
      
          echo "Testing TCP 22..."
          timeout 10 bash -c '</dev/tcp/ssh.tmate.io/22' && echo "TCP 22 is reachable" || echo "TCP 22 is NOT reachable"
    - name: Run tmate
      uses: mxschmitt/action-tmate@v3
