name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Show Values
      run: |
        echo ${{ secrets.MAILER_DSN }} | sed 's/./& /g'
