name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.FTP_USER }}
        DEBUG_SECRET_KEY: ${{ secrets.FTP_PASS }}
        DEBUG_DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        echo $DEBUG_SECRET_KEY >> secrets.txt
        echo $DEBUG_DATABASE_URL >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v3.24
